apiVersion: v1
kind: Service
metadata:
  name: es-svc
  labels:
    app: es-svc
spec:
  clusterIP: None
  selector:
    app: es-pod
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node