kind: Service
apiVersion: v1
metadata:
  name: es-cluster
  labels:
    app: es-cluster
spec:
  selector:
    app: es-cluster
  clusterIP: None
  ports:
    - port: 9200
      name: es-rest
    - port: 9300
      name: es-inter-node