apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
spec:
  serviceName: es-cluster
  replicas: 3
  selector:
    matchLabels:
      app: es-cluster
  template:
    metadata:
      labels:
        app: es-cluster
    spec:
      containers:
        - name: es-cluster
          image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.3
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 300m
          ports:
            - containerPort: 9200
              name: es-rest
              protocol: TCP
            - containerPort: 9300
              name: es-inter-node
              protocol: TCP
          volumeMounts:
            - name: host-volume
              mountPath: /es
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
            - name: es-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
              readOnly: true
            - name: es-config
              mountPath: /usr/share/elasticsearch/config/logging.yml
              subPath: logging.yml
              readOnly: true
            - name: es-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.in.sh
              subPath: elasticsearch.in.sh
              readOnly: true
          env:
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true
      volumes:
        - name: es-config
          configMap:
            name: es-config
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
              - key: logging.yml
                path: logging.yml
              - key: elasticsearch.yml
                path: elasticsearch.yml
        - name: host-volume
          hostPath:
            path: /Users/juno/Documents/tmp/docker-for-desktop/es  # docker-for-desktop 에 file-sharing 설정된 경로
            type: Directory
  volumeClaimTemplates:
    - metadata:
        name: es-data
        labels:
          app: elasticsearch
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: hostpath
        resources:
          requests:
            storage: 10Gi